/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    'accounting-category': RouteRecordInfo<'accounting-category', '/accounting-category', Record<never, never>, Record<never, never>>,
    'accounting-charts': RouteRecordInfo<'accounting-charts', '/accounting-charts', Record<never, never>, Record<never, never>>,
    'accounting-dashboard': RouteRecordInfo<'accounting-dashboard', '/accounting-dashboard', Record<never, never>, Record<never, never>>,
    'accounting-journals': RouteRecordInfo<'accounting-journals', '/accounting-journals', Record<never, never>, Record<never, never>>,
    'accounting-journals-add-entry': RouteRecordInfo<'accounting-journals-add-entry', '/accounting-journals-add-entry', Record<never, never>, Record<never, never>>,
    'accounting-journals-entry': RouteRecordInfo<'accounting-journals-entry', '/accounting-journals-entry', Record<never, never>, Record<never, never>>,
    'accounting-settings': RouteRecordInfo<'accounting-settings', '/accounting-settings', Record<never, never>, Record<never, never>>,
    'error': RouteRecordInfo<'error', '/error', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
  }
}
